# Generated by Django 5.0.1 on 2024-03-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
                ("text", models.TextField(verbose_name="本文")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
            ],
        ),
        migrations.AlterField(
            model_name="chat",
            name="chat_room_id",
            field=models.IntegerField(verbose_name="チャットルームID"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="投稿日時"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="submission",
            field=models.TextField(verbose_name="メッセージ"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="最終更新日時"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="user_id",
            field=models.IntegerField(verbose_name="ユーザーID"),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="チャットルーム名"
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="like",
            name="chat_id",
            field=models.IntegerField(verbose_name="チャットID"),
        ),
        migrations.AlterField(
            model_name="like",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
        ),
        migrations.AlterField(
            model_name="like",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="最終更新日時"),
        ),
        migrations.AlterField(
            model_name="like",
            name="user_id",
            field=models.IntegerField(verbose_name="ユーザーID"),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="メールアドレス"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="アクティブ"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=True, verbose_name="スタッフ"),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ニックネーム"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="最終更新日時"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, verbose_name="ユーザー名"),
        ),
    ]
