# Generated by Django 5.0.1 on 2024-03-02 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("firstapp", "0003_alter_user_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="likes_count",
        ),
    ]
